PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?type
WHERE {
    ?individual rdf:type ?type .
    FILTER(isIRI(?type))
    FILTER (?type NOT IN (
        owl:Class,
        rdf:List,
        rdf:Property,
        rdfs:Class,
        rdfs:Datatype,
        rdfs:ContainerMembershipProperty,
        owl:DatatypeProperty,
        owl:FunctionalProperty,
        owl:InverseFunctionalProperty,
        owl:ObjectProperty,
        owl:TransitiveProperty,
        owl:SymmetricProperty,
        owl:NamedIndividual,
        owl:Ontology
    ))
}
ORDER BY ?type
LIMIT 1000
